### PR TITLE
:ship: use normal user instead of root

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
@adamgraves-choices - can you rebase this which should hopefully address the broken build.

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://connecting-to-services-pr-265.dev.c2s.nhschoices.net](http://connecting-to-services-pr-265.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://connecting-to-services-pr-265.dev.c2s.nhschoices.net](http://connecting-to-services-pr-265.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
@adamgraves-choices The branch needs updating please. There are changes made to 'dockerise' this repo with `docker-compose` files but they are sat in PR #271 atm. Probably not worth making those changes in this PR but when #271 gets merged there will need to be some tweaks to the `docker-compose` files. And the removal of `prepublish` from `package.json` will also need to be done /cc @ajthomascouk

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://connecting-to-services-pr-265.dev.c2s.nhschoices.net](http://connecting-to-services-pr-265.dev.c2s.nhschoices.net)

**Comment by st3v3nhunt** [comment]
Closing this as I've rebased and created a new branch/PR #274 
Issues have been created for the additional notes I've made in the comments here.
@adamgraves-choices Can you review #274 please?

**Pull request closed without merging**
