### PR TITLE
Update with new NHS.UK frontend library

### PR DESCRIPTION
**Pull request by davidhunter08**
## Description

Updated files to use the new NHS.UK frontend library.

Changes include:
- added NHS.UK frontend as a dependency
- removed all existing Sass
- updated page templates
- updated components (grid, header, footer, breadcrumb etc.)
- updated tests

## Motivation and Context

The service will no be more consistent with NHS.uk and easier to update/maintain.

## Checklist

- [x] New and/or updated tests
- [x] Changes log in `CHANGELOG`

### CODE REVIEW

**Comment by davidhunter08** [comment]
@AdamChrimes could you please look at the Javascript?

The Javascript from the NHS.Uk frontend needs adding in.

**Comment by AdamChrimes** [comment]
@davidhunter08 can you flag this with the feature team to look at the JavaScript?

**Comment by davidhunter08** [comment]
@AdamChrimes it was flagged with the team on 22 July 2019.

**Comment by neilbmclaughlin** [comment]
Closing the PR for now as it is likely to be superseded by the work in Jira ticket CI2-1018.

**Pull request closed without merging**
