### PR TITLE
:ghost who you gonna call

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-313.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-313.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-313.dev.beta.nhschoices.net)

**Comment by st3v3nhunt** [comment]
Please add a PR template (https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) with a check to update the version as part of this change so as stop this from happening again.

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-313.dev.beta.nhschoices.net)

**Pull request merged**
