### PR TITLE
Feature/sass env

### PR DESCRIPTION
**Pull request by ajthomascouk**
Simple find and replace of font URL, no clever environment variable settings.

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
The PR was un-mergeable with a broken PR build due to the corrupted .travis.yml file in commit f99535e. Repeating the build generated the same error. Fixed it by pushing a blank line change and then reverting the change and force pushing. This makes it apparent that I'm not really sure what the PR build is doing. Suspect that the answer is in the description but it is not explicit [here](https://docs.travis-ci.com/user/pull-requests#My-Pull-Request-isn%E2%80%99t-being-built).

Rebasing may have also achieved the same thing.

**Comment by neilbmclaughlin** [comment]
Needs rebasing.

**Comment by ajthomascouk** [comment]
Remove 'replace' module and use 'replaceinfiles' instead.

**Comment by ajthomascouk** [comment]
Closing this as its been done as part of PR #229

**Pull request closed without merging**
