### PR TITLE
:microscope: Check opening times with alterations works

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
Pull request created to facilitate testing.

Not intended for merge.

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
The env var PHARMACY_LIST_PATH has been defined on the Heroku review app so it points at the limited pharmacy list with an alteration defined for today(28th Oct 2016) for the pharmacy FYY76 at post code PE10 9NB.

See https://connecting-to-services-pr-157.herokuapp.com/finders/results?location=PE10+9NB&open=true&context=

**Comment by neilbmclaughlin** [comment]
@st3v3nhunt once you are happy with [PR35](https://github.com/nhsuk/moment-opening-times/pull/35) this can be closed and the branch deleted.

**Comment by st3v3nhunt** [comment]
[Add exceptional opening times/dates](https://trello.com/c/8gHrmhJO/502-add-exceptional-opening-times-dates)

**Comment by neilbmclaughlin** [comment]
No longer required.

**Pull request closed without merging**
