### PR TITLE
:one::one::one: add 111 call out

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
@ajthomascouk Can you add/extend a test to check for the message on the various result page configurations please?

**Comment by st3v3nhunt** [comment]
The spacing on the message needs a bit of a tweak for a results page with only nearby results. See the screenshot. 
screen shot 2017-12-13 at 11 36 04

At the moment this URL will show the same as the image but that will change the next time it is restarted. https://connecting-to-services-pr-417.dev.beta.nhschoices.net/find-a-pharmacy/results?location=tr21

**Comment by ajthomascouk** [comment]
Tests added and spacing sorted

**Comment by st3v3nhunt** [comment]
@ajthomascouk I can't see the changes for the spacing in https://github.com/nhsuk/connecting-to-services/pull/417/commits/11ffc67b96e9eeb73dc09633aa6a8a421df051b8

**Pull request merged**
