### PR TITLE
:grin: track user scroll and phone number clicks

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
:rocket: deployed to [http://connecting-to-services-pr-259.dev.c2s.nhschoices.net](http://connecting-to-services-pr-259.dev.c2s.nhschoices.net) and using the latest release of nearby-services-api (0.2.0-beta)

**Comment by ajthomascouk** [comment]
[Apply custom analytics tracking](https://trello.com/c/r6NujHcL/601-apply-custom-analytics-tracking)

**Comment by st3v3nhunt** [comment]
@ajthomascouk Is this change something that still wants to get integrated into the app?
If so can you rebase it please?

**Comment by neilbmclaughlin** [comment]
@ajthomascouk - is this still WIP? Is there anything which can be done to get it moved forward?

**Comment by ajthomascouk** [comment]
@neilbmclaughlin wrote:
> is this still WIP? 
Yeah

> Is there anything which can be done to get it moved forward?
Not at this stage. I need to catch up with Nick Gallon.

**Comment by neilbmclaughlin** [comment]
I'm un-assigning myself from this - re-request when it need reviewing

**Comment by st3v3nhunt** [comment]
@ajthomascouk Is this still valid or can it be closed? There has been no change on it for ~5 weeks now.

**Comment by ajthomascouk** [comment]
Will revisit this at somepoint.

**Pull request closed without merging**
