### PR TITLE
Feature/serve css

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by ajthomascouk** [comment]
[Serve compressed CSS for live, standard for dev](https://trello.com/c/NQDG9Jvw/682-serve-compressed-css-for-live-standard-for-dev)

**Comment by neilbmclaughlin** [comment]
Can you rebase this one too.

**Comment by ajthomascouk** [comment]
Need to rebranch this from PR #229

**Comment by ajthomascouk** [comment]
I'm going to close this for now as it will need to be done as a new branch of #236 post docker work.

**Pull request closed without merging**
