### PR TITLE
Feature/snyk run reduction

### PR DESCRIPTION
**Pull request by st3v3nhunt**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-311.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-311.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-311.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-311.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-311.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-311.dev.beta.nhschoices.net)

**Comment by st3v3nhunt** [comment]
@markysoft Sorry. I should have put a `WIP` label on - a few other things to do on it before it is ready for merging

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-311.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of connecting-to-services succeeded (http://connecting-to-services-pr-311.dev.beta.nhschoices.net)

**Comment by st3v3nhunt** [comment]
@markysoft Good to go now, thanks!

**Pull request merged**
