### PR TITLE
:interrobang: Add exceptional opening times support

### PR DESCRIPTION
**Pull request by st3v3nhunt**

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
[Add exceptional opening times/dates](https://trello.com/c/8gHrmhJO/502-add-exceptional-opening-times-dates)

**Comment by neilbmclaughlin** [comment]
Significant increase in test execution times with the new moment-opening-times:

**master**
  Nearby
    happy path
      ✓ should return an object with nearby and open services (90ms)

vs

**feautre/exceptional-opening-times**
  Nearby
    happy path
      ✓ should return an object with nearby and open services (391ms)

Will investigate the cause of this and possible solutions.

**Comment by st3v3nhunt** [comment]
Yikes! I thought it had gone slow but somehow didn't twig :rage:

Who was saying performance testing should be de-prioritised!

**Comment by st3v3nhunt** [comment]
I'm closing this PR and opening another against the branch `feature/exceptional-opening-times`. I misspelled `feature` as `feautre` on this branch and it has been driving me nuts.

**Comment by st3v3nhunt** [comment]
New PR #186

**Pull request closed without merging**
