### PR TITLE
:boom: IE styles

### PR DESCRIPTION
**Pull request by ajthomascouk**

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
:rocket: deployed to [http://connecting-to-services-pr-258.dev.c2s.nhschoices.net](http://connecting-to-services-pr-258.dev.c2s.nhschoices.net) and using the latest release of nearby-services-api (0.2.0-beta)

**Comment by ajthomascouk** [comment]
[Fix CSS in IE (and other browsers)](https://trello.com/c/upSwKgmV/719-fix-css-in-ie-and-other-browsers)

**Comment by neilbmclaughlin** [comment]
@ajthomascouk - might be easiest if you talked me through the changes using browser stack for me to review this.

**Comment by neilbmclaughlin** [comment]
@ajthomascouk walked me through the changes. LGTM.

**Pull request merged**
